New upstream version 110.99

diff --git a/config/_heap2exec b/config/_heap2exec
--- a/config/_heap2exec
+++ b/config/_heap2exec
@@ -1,10 +1,26 @@
 #!@SHELL@
+#
+# COPYRIGHT (c) 2019 The Fellowship of SML/NJ (http://www.smlnj.org)
+# All rights reserved.
+#
+# usage: heap2exec [ <options> ] heapfile execfile
+#
+# where the options are
+#
+#	-static
+#	-linkwith-a	-- use static linking on Linux/FreeBSD systems
+#
+#	-dynamic
+#	-linkwith-so	-- use dynamic linking on Linux/FreeBSF systems
+#
 
 CMD=`basename "$0"`
 
 usage() {
-	echo "usage: $CMD [--linkwith-<format>] heapfile execfile"
-	echo "       <format> = exec | so | a"
+	echo "usage: $CMD [ -32 | -64 ] [ <link> ] <heapfile> <execfile>"
+	echo "  where <link> is one of"
+	echo "      -static,  --linkwith-a    -- use static linking (Linux/FreeBSD)"
+	echo "      -dynamic, --linkwith-so   -- use dynamic linking (Linux/FreeBSD)"
 	exit 1
 }
 
@@ -13,13 +29,23 @@ die () {
 	exit 1
 }
 
+# the default size; this is set by the config/install.sh script
+#
+SIZE=@SIZE@
+if [ x"$1" = x-32 ] ; then
+  SIZE=32 ; shift
+elif [ x"$1" = x-64 ] ; then
+  SIZE=64 ; shift
+fi
+SIZE_OPT="-"$SIZE
+
 if [ x${SMLNJ_HOME} = x ] ; then
     BIN_DIR="@BINDIR@"
 else
     BIN_DIR=${SMLNJ_HOME}/bin
 fi
 
-ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys"`
+ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys" $SIZE_OPT`
 if [ "$?" != "0" ]; then
 	die "unable to determine architecture/operating system"
 fi
@@ -32,40 +58,40 @@ H2A=${BIN_DIR}/heap2asm
 
 FORMAT=
 if [ $# != 2 ] ; then
-	if [ $# = 3 ] ; then
-		case $1 in
-			--linkwith-exec)
-				FORMAT=exec
-				;;
-			--linkwith-so)
-				FORMAT=so
-				;;
-			--linkwith-a)
-				FORMAT=a
-				;;
-			*)
-				usage
-				;;
-		esac
-		shift
-   	else
+    if [ $# = 3 ] ; then
+	case $1 in
+	    --linkwith-exec)
+		FORMAT=exec
+		;;
+	    -dynamic|--linkwith-so)
+		FORMAT=so
+		;;
+	    -static|--linkwith-a)
+		FORMAT=a
+		;;
+	    *)
 		usage
-	fi
+		;;
+	esac
+	shift
+    else
+	usage
+    fi
 else
-	case ${OPSYS} in
-		darwin)
-			FORMAT=exec
-			;;
-		freebsd|linux)
-			FORMAT=a
-			;;
-		*)
-			die "no default runtime link format known for ${OPSYS}"
-			;;
-		esac
+    case ${OPSYS} in
+	darwin)
+	    FORMAT=exec
+	    ;;
+	freebsd|linux)
+	    FORMAT=a
+	    ;;
+	*)
+	    die "no default runtime link format known for ${OPSYS}"
+	    ;;
+	esac
 fi
 if [ -z "$FORMAT" ] ; then
-	die "no runtime object format specified"
+    die "no runtime object format specified"
 fi
 
 heapfile=$1
@@ -85,70 +111,75 @@ A_FLAGS=
 A_LIBS=
 
 case ${OPSYS} in
-	darwin)
-		EXEC_PROG=${LD}
-		EXEC_LIBS=-lc
-		;;
-	freebsd)
-		SO_PROG=${CC}
-		SO_FLAGS=-Wl,--export-dynamic
-		SO_LIBS=-lm
-		A_PROG=${CC}
-		A_FLAGS=-Wl,--export-dynamic
-		A_LIBS=-lm
-		;;
-	linux)
-		SO_PROG=${CC}
-		SO_FLAGS=-Wl,--export-dynamic
-		A_PROG=${CC}
-		A_FLAGS=-Wl,--export-dynamic
-		A_LIBS="-lm -ldl"
-		;;
-	*)
-		;;
+    darwin)
+	EXEC_PROG=${LD}
+	EXEC_LIBS=-lc
+	;;
+    freebsd)
+	SO_PROG=${CC}
+	SO_FLAGS=-Wl,--export-dynamic
+	SO_LIBS=-lm
+	A_PROG=${CC}
+	A_FLAGS=-Wl,--export-dynamic
+	A_LIBS=-lm
+	;;
+    linux)
+	SO_PROG=${CC}
+	SO_FLAGS=-Wl,--export-dynamic
+	A_PROG=${CC}
+	A_FLAGS=-Wl,--export-dynamic
+	A_LIBS="-lm -ldl"
+	;;
+    *)
+	;;
 esac
 
 if [ ! -f $H2A ]; then
-	echo "${CMD}: heap2asm is not installed"
-	exit 2
+    echo "${CMD}: heap2asm is not installed"
+    exit 2
 fi
 
+#
+# TODO: it would be better to check the linking command etc before
+# running heap2asm, since that can take a long time
+#
+
 RESULT=0
-if ${H2A} "$heapfile" "$execfile".s ; then
-	if [ -f "$execfile".s ] ; then
-		if ${CC} -c -o "$execfile".o "$execfile".s ; then
-			rm "$execfile".s
-		else
-			rm "$execfile".s
-			die "${execfile}.o creation failed"
-		fi
+if ${H2A} $SIZE_OPT "$heapfile" "$execfile".s ; then
+    if [ -f "$execfile".s ] ; then
+	if ${CC} -c -o "$execfile".o "$execfile".s ; then
+	    rm "$execfile".s
 	else
-		die "${execfile}.s creation failed"
+	    rm "$execfile".s
+	    die "${execfile}.o creation failed"
 	fi
-	if [ "$FORMAT" = exec -a -f "${RUNX}" ] ; then
-		[ -z "${EXEC_PROG}" ] && die "no linker specified for runtime format $FORMAT"
-		${EXEC_PROG} ${EXEC_FLAGS} -o "$execfile" ${RUNX} "$execfile".o ${EXEC_LIBS}
-		RESULT=$?
-	elif [ "$FORMAT" = so -a -f "${RUN_SO}" ] ; then
-		[ -z "${SO_PROG}" ] && die "no linker specified for runtime format $FORMAT"
-		${SO_PROG} ${SO_FLAGS} -o "$execfile" ${RUN_SO} "$execfile".o ${SO_LIBS}
-		RESULT=$?
-	elif [ "$FORMAT" = a -a -f "${RUN_A}" ] ; then
-		[ -z "${A_PROG}" ] && die "no linker specified for runtime format $FORMAT"
-		${A_PROG} ${A_FLAGS} -o "$execfile" ${RUN_A} "$execfile".o ${A_LIBS}
-		RESULT=$?
-	else
-		echo "${CMD}: linkable runtime system object ($FORMAT) not available"
-		rm "$execfile".o
-		exit 2
-	fi
+    else
+	die "${execfile}.s creation failed"
+    fi
+    if [ "$FORMAT" = exec -a -f "${RUNX}" ] ; then
+	[ -z "${EXEC_PROG}" ] && die "no linker specified for runtime format $FORMAT"
+	${EXEC_PROG} ${EXEC_FLAGS} -o "$execfile" ${RUNX} "$execfile".o ${EXEC_LIBS}
+	RESULT=$?
+    elif [ "$FORMAT" = so -a -f "${RUN_SO}" ] ; then
+	[ -z "${SO_PROG}" ] && die "no linker specified for runtime format $FORMAT"
+	${SO_PROG} ${SO_FLAGS} -o "$execfile" ${RUN_SO} "$execfile".o ${SO_LIBS}
+	RESULT=$?
+    elif [ "$FORMAT" = a -a -f "${RUN_A}" ] ; then
+	[ -z "${A_PROG}" ] && die "no linker specified for runtime format $FORMAT"
+	${A_PROG} ${A_FLAGS} -o "$execfile" ${RUN_A} "$execfile".o ${A_LIBS}
+	RESULT=$?
+    else
+	echo "${CMD}: linkable runtime system object ($FORMAT) not available"
 	rm "$execfile".o
+	exit 2
+    fi
+    rm "$execfile".o
 else
-	die "heap2asm failed"
+    die "heap2asm failed"
 fi
 
 if [ $RESULT != 0 ] ; then
-	die "linking failed with return code $RESULT"
+    die "linking failed with return code $RESULT"
 fi
 
 exit 0
diff --git a/config/_run-sml b/config/_run-sml
--- a/config/_run-sml
+++ b/config/_run-sml
@@ -1,5 +1,8 @@
 #!@SHELL@
 #
+# Copyright 2019 The Fellowship of SML/NJ (http://www.smlnj.org)
+# All rights reserved.
+#
 # The standard driver for SML/NJ under the new runtime system
 #
 
@@ -22,7 +25,7 @@ unset ENV
 
 # On cygwin, make sure SMLNJ_HOME is given a POSIX-style pathname.
 if [ x"$SMLNJ_HOME" != x ] ; then
-   if [ x"$SMLNJ_CYGWIN_RUNTIME" != x ] ; then 
+   if [ x"$SMLNJ_CYGWIN_RUNTIME" != x ] ; then
       if [ "`uname -o`" = "Cygwin" ] ; then
          # Convert to Unix style, absolute pathname.
          SMLNJ_HOME=`cygpath -u -a "$SMLNJ_HOME"`
@@ -54,16 +57,6 @@ RUN_DIR=$BIN_DIR/.run
 # the path of the directory in which the heap images are kept.
 HEAP_DIR=$BIN_DIR/.heap
 
-#
-# the following could be replaced with some site specific code
-#
-ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys"`
-if [ "$?" != "0" ]; then
-  echo "$CMD: unable to determine architecture/operating system"
-  exit 1
-fi
-eval $ARCH_N_OPSYS
-
 #############################################################################
 #
 # END SITE SPECIFIC STUFF
@@ -88,12 +81,22 @@ fi
 
 ALLOC=""
 
+# the default size; this is set by the config/install.sh script
+#
+SIZE_OPT="-"@SIZE@
+
+# if "yes" then we report the heap suffix and quit
+#
+REPORT_SUFFIX=no
+
 #
 # Process command line arguments
 #
 while [ "$#" != "0" ]; do
   arg=$1
   case "$arg" in
+    -32) shift; SIZE_OPT=$arg ;;
+    -64) shift; SIZE_OPT=$arg ;;
     @SMLrun=*)
       shift
       RUN=`echo $arg | sed 's/@SMLrun=//'`
@@ -115,9 +118,16 @@ while [ "$#" != "0" ]; do
       echo "$CMD @VERSION@"
       exit 0
       ;;
-    @SMLsuffix)
-      echo "$HEAP_SUFFIX"
+    @SMLwordsize)
+      case $SIZE_OPT in
+	-32) echo "32" ;;
+	-64) echo "64" ;;
+      esac
       exit 0
+      ;;
+    @SMLsuffix)
+      shift
+      REPORT_SUFFIX=yes
       ;;
     @SMLalloc=*)
       shift
@@ -128,6 +138,23 @@ while [ "$#" != "0" ]; do
       ;;
   esac
 done
+
+#
+# the following could be replaced with some site specific code
+#
+ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys" $SIZE_OPT`
+if [ "$?" != "0" ]; then
+  echo "$CMD: unable to determine architecture/operating system"
+  exit 1
+fi
+eval $ARCH_N_OPSYS
+
+# if the `@SMLsuffix` option was specified, then report the suffix and quit
+#
+if [ $REPORT_SUFFIX = yes ] ; then
+    echo $HEAP_SUFFIX
+    exit 0
+fi
 
 #
 # Try to figure out the CPU's cache size and set the allocation area
@@ -156,7 +183,7 @@ if [ "$ALLOC" = "" ] ; then
 	    esac
 	else
 	    kb=`echo $cache | sed -e 's/^[^0-9]*\([0-9]*\).*$/\1/'`
-	    case $kb in 
+	    case $kb in
 		128)
 		    # This is the Celeron case.
 		    # ALLOC="@SMLalloc=32k"
